language: python

# Supported Python versions
python:
  - "3.5"
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database unsullied_todo' -U postgres

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# Run tests
script:
  - python todoList/manage.py makemigrations
  - python todoList/manage.py migrate
  - cd todoList
  - python manage.py test

# Generate coverage report
after_success:
  - coveralls

cache: pip